name: Update Candy Icons
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-icons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: hyde
      - uses: actions/checkout@v4
        with:
          path: Icon_Candy
          repository: EliverLara/candy-icons
          ref: master
      - uses: actions/checkout@v4
        with:
          path: sweet-folder
          repository: EliverLara/Sweet-folders
          ref: master
      - name: Archives
        run: |
          tar -czf hyde/Source/arcs/Icon_Candy.tar.gz Icon_Candy
          mv sweet-folder/Sweet-Rainbow Gtk_SweetRainbow
          tar -czf hyde/Source/arcs/Gtk_SweetRainbow.tar.gz Gtk_SweetRainbow
      - name: Commit
        working-directory: hyde
        run: |
          git config --global user.name 'github-action[bot]'
          git config --global user.email 'github-action@users.noreply.github.com'
          git add Source/arcs/Icon_Candy.tar.gz Source/arcs/Gtk_SweetRainbow.tar.gz
          git commit -am "Workflow update icons"
          git push
